### ISSUE TITLE
Add schema to publisher page table

### ISSUE THREAD

**Issue by trickvi** [okfn/spend-publishing-dashboard#37]
This shows against what a source file is validated.

**Comment by georgiana-b** [comment]
The schema used to validate a source file can vary depending on the options passed to [GoodTables schema processor](https://github.com/frictionlessdata/goodtables/blob/master/goodtables/processors/schema.py#L84) so we need a way to store it in order to show it in the dashboard. One option could be to store the schemas in or along with the other tabular files. Another option is to use [jsontableschema-py storage functionality](https://github.com/frictionlessdata/jsontableschema-py#storage) and keep them somewhere separately.  We have to decide if and where we want to store them.

**Comment by pwalsh** [comment]
The schema is passed in via a field on the sources.csv file called `schema`: https://github.com/okfn/data-quality-uk-25k-spend/blob/master/data/sources.csv

It is already stored at this URL, so there is no need to store it in any other way.

The feature request here is to add a column to the table called "schema", and link to the schema file, just like we do in the current "URL" column for the source file itself.

**Comment by pwalsh** [comment]
FIXED.
